# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: ilhicas
email: blog@ilhicas.com
description: >
  A DevOps Padawan Journey
logo: "/assets/images/logo.png"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ilhicas.com" # the base hostname & protocol for your site
paginate:	5 # The number of posts to show per page on your homepage

name: 'André Ilhicas dos Santos'
bio: >
  Devops Padawan, curious about systems automation, learning new languages, paradigms tools each day.
author_image: "/assets/images/gitprofile.png"
twitter_username: ilhicas
github_username:  ilhicas

# Google Analytics
analytics_id: "UA-INSERTVALIDCODE-1"

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

gems:
  - jekyll-paginate
